### PR TITLE
New translation tokens and strings (English)

### PR DESCRIPTION
**Pull request by leac**
Hi

Please see if you can add attached new English translation tokens and strings.
Accidentally I formatted the spaces in the file, according to Moodle HQ settings. Hope it's not an issue.

Kindly
Lea
ORT Israel

### CODE REVIEW

**Comment by sensei-hacker** [comment]
Before I saw your comment, I was going to ask you to make sure it conformed to the style checked by
https://moodle.org/plugins/local_codechecker

:)   I no longer have a Moodle installation handy to test this, has it been tested and validated by someone other than the developer?  Same question for the Hebrew.

**Comment by leac** [comment]
@nadavkav, would you please QA this?

**Comment by nadavkav** [comment]
As Moodle Hebrew translation team member, I can confirm the strings are proper. 
Also, the code looks fine too.
+1 for this PR :smile:

**Comment by nadavkav** [comment]
As this plugin is not on Moodle HQ plugins repository, you (@leac) could send another PR with the Hebrew translation too, once this is accepted.

Hi @MorrisR2 , Am I to understand that you are not maintaining this repo any more?

**Comment by sensei-hacker** [comment]
@nadavkav
I'm happy to accept any pull requests, etc. It hasn't needed much maintenance in the last couple of years. However, if someone else would like to take over, that's fine as well.

**Comment by nadavkav** [comment]
@MorrisR2 Thank you. we'll consider it :-)

**Comment by leac** [comment]
Hi @MorrisR2 

I was wondering if you would be willing to accept this PR, now that @nadavkav, a Moodle Hebrew translation team member, tested it and confirmed that the strings are proper?

**Pull request merged**
